py_library(
    name = "mcSim-cover-lib",
    src = [
        "cover.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//ecs/lib:ecs-component-lib",
    ],
)

py_library(
    name = "mcSim-roll-bonus-lib",
    src = [
        "rollBonus.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//ecs/components:ecs-value-component-lib",
    ],
)

py_library(
    name = "mcSim-target-number-lib",
    src = [
        "targetNumber.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//ecs/components:ecs-value-component-lib",
    ],
)
