py_library(
    name = "tuples-lib",
    srcs = [
        "tuples.py"
    ],
    visibility = ["//visibility:public"],
    deps = [
        
    ]
)

py_library(
    name = "report-writer-lib",
    srcs = [
        "writer.py"
    ],
    visibility = ["//visibility:public"],
    deps = [
    ]
)