py_library(
    name = "report-system-lib",
    srcs = [
        "report.py"
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//ecs/lib:ecs-factory",
        "//ecs/lib:ecs-system"
    ]
)